package io.openems.edge.heat.shi;

import org.osgi.service.metatype.annotations.AttributeDefinition;
import org.osgi.service.metatype.annotations.ObjectClassDefinition;

import io.openems.common.types.MeterType;

@ObjectClassDefinition(//
		name = "Heat SHI Heat Pump", //
		description = "Reads and writes SHI heat pump values via Modbus.")
@interface Config {

	@AttributeDefinition(name = "Component-ID", description = "Unique ID of this Component")
	String id() default "heatPump0";

	@AttributeDefinition(name = "Alias", description = "Human-readable name of this Component; defaults to Component-ID")
	String alias() default "";

	@AttributeDefinition(name = "Is enabled?", description = "Is this Component enabled?")
	boolean enabled() default true;

	@AttributeDefinition(name = "Modbus-ID", description = "ID of Modbus bridge.")
	String modbus_id() default "modbus0";

	@AttributeDefinition(name = "Modbus Unit-ID", description = "Modbus Unit-ID of the heat pump.")
	int modbusUnitId() default 1;

	@AttributeDefinition(name = "Read only", description = "If enabled, OpenEMS reads values but does not write setpoints.")
	boolean readOnly() default false;

	@AttributeDefinition(name = "Meter-Type", description = "Use CONSUMPTION_METERED if the heat pump is connected behind the grid meter (its consumption is included in the grid measurement). Use CONSUMPTION_NOT_METERED if it is connected grid-side of the grid meter and therefore not part of the calculated consumption.")
	MeterType type() default MeterType.CONSUMPTION_METERED;

	@AttributeDefinition(name = "Modbus target filter", description = "Auto-generated by 'Modbus-ID'.")
	String Modbus_target() default "(enabled=true)";

	String webconsole_configurationFactory_nameHint() default "Heat SHI Heat Pump [{id}]";
}
